name: Build with Briefcase

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Briefcase and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Create and Build App
        run: |
          briefcase create
          briefcase build macOS --no-sign
          briefcase package macOS --no-sign

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: CADSimplifier-macOS
          path: macOS/dist/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Briefcase and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Create and Build App
        run: |
          briefcase create
          briefcase build
          briefcase package

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: CADSimplifier-Windows
          path: windows/dist/*.exe
